// Package hooks implements pre-commit config generation and installation.
package hooks

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/aredgwell/athena/internal/config"
)

// InstallOptions controls hook installation behavior.
type InstallOptions struct {
	RepoRoot   string
	PreCommit  bool
	ConfigOnly bool // only generate config, don't install hooks
	DryRun     bool
}

// InstallResult holds the outcome of hook installation.
type InstallResult struct {
	ConfigPath string   `json:"config_path,omitempty"`
	HookPath   string   `json:"hook_path,omitempty"`
	Created    []string `json:"created,omitempty"`
	Updated    []string `json:"updated,omitempty"`
	DryRun     bool     `json:"dry_run"`
}

// Install generates and optionally installs pre-commit hooks.
func Install(cfg config.HooksConfig, opts InstallOptions) (*InstallResult, error) {
	result := &InstallResult{DryRun: opts.DryRun}

	if !cfg.PreCommit && !opts.PreCommit {
		return result, nil
	}

	// Generate pre-commit config
	configContent := generatePreCommitConfig()
	configPath := filepath.Join(opts.RepoRoot, ".pre-commit-config.yaml")
	result.ConfigPath = configPath

	if opts.DryRun {
		return result, nil
	}

	// Write config file
	existing, _ := os.ReadFile(configPath)
	if string(existing) != configContent {
		if err := os.WriteFile(configPath, []byte(configContent), 0o644); err != nil {
			return nil, fmt.Errorf("writing pre-commit config: %w", err)
		}
		if len(existing) > 0 {
			result.Updated = append(result.Updated, configPath)
		} else {
			result.Created = append(result.Created, configPath)
		}
	}

	if opts.ConfigOnly {
		return result, nil
	}

	// Install git hook script
	hookDir := filepath.Join(opts.RepoRoot, ".git", "hooks")
	if err := os.MkdirAll(hookDir, 0o755); err != nil {
		return result, fmt.Errorf("creating hooks dir: %w", err)
	}

	hookPath := filepath.Join(hookDir, "pre-commit")
	result.HookPath = hookPath

	hookScript := generateHookScript()
	existingHook, _ := os.ReadFile(hookPath)
	if string(existingHook) != hookScript {
		if err := os.WriteFile(hookPath, []byte(hookScript), 0o755); err != nil {
			return result, fmt.Errorf("writing hook: %w", err)
		}
		if len(existingHook) > 0 {
			result.Updated = append(result.Updated, hookPath)
		} else {
			result.Created = append(result.Created, hookPath)
		}
	}

	return result, nil
}

func generatePreCommitConfig() string {
	var b strings.Builder
	b.WriteString("# Generated by athena hooks install\n")
	b.WriteString("repos:\n")
	b.WriteString("  - repo: local\n")
	b.WriteString("    hooks:\n")
	b.WriteString("      - id: athena-check\n")
	b.WriteString("        name: athena check\n")
	b.WriteString("        entry: athena check\n")
	b.WriteString("        language: system\n")
	b.WriteString("        pass_filenames: false\n")
	b.WriteString("      - id: athena-commit-lint\n")
	b.WriteString("        name: athena commit lint\n")
	b.WriteString("        entry: athena commit lint --from HEAD~1\n")
	b.WriteString("        language: system\n")
	b.WriteString("        stages: [commit-msg]\n")
	b.WriteString("        pass_filenames: false\n")
	return b.String()
}

func generateHookScript() string {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# Generated by athena hooks install\n")
	b.WriteString("set -e\n")
	b.WriteString("\n")
	b.WriteString("# Run athena check on staged changes\n")
	b.WriteString("athena check\n")
	return b.String()
}
